### ISSUE TITLE
Current datetimepicker is quite confusing

### ISSUE THREAD

**Issue by chez14** [ftisunpar/BlueTape#26]
A person have reported that the `time` part of current datetimepicker is confusing. I've asked him several alternative, and suggested to use [xdsoft](https://xdsoft.net/jqplugins/datetimepicker/)'s picker.

What do you think? I'm currently implementing it on my local copy, if you think it's ok to go, i'll submit a PR.

**Update**: Sorry, i got miss-com.

**Comment by pascalalfadian** [comment]
Hi @chez14. Thank you for your suggestion. If that "person" is not Ci Joanna, then that makes two of them (#11).

Please give me some time to think about, and remind me about after FRS, because:

* There's a skripsi topic to convert all frontend to Bootstrap, which makes it easier to choose date/time picker (even for eonasdan's). If I remember correctly, someone has registered for that topic but cancelled. Will confirm after FRS.
* There's already another branch going on, i.e. `heroku` because I am moving out from Azure. Although it's backend stuffs, but still it could have a conflict or something
* Modern web browsers starting to support native date/time picker.

**Comment by chez14** [comment]
It's actually from Ko Rickie hahah...

Got it, i'll inform the person first, then.

**Comment by pascalalfadian** [comment]
Hi @chez14 are you still interested in submitting PR? If so, I think you can go on, because:

* I checked again the skripsi topic is a bintang (*) topic, and very unlikely to be taken
* I think you can even send 2 PR's from the same branch: one for `master` and one for `heroku`

What do you think? Let me know.

**Comment by chez14** [comment]
Got it, I'll send the PRs soon.

**Comment by chez14** [comment]
As the PR were merged, I'm closing this issue.

**Comment by pascalalfadian** [comment]
Yep, it worked both in Heroku and Azure. Thanks!
